### ISSUE TITLE
Serious error in introduction.html

### ISSUE THREAD

**Issue by jribbens** [html5doctor/diveintohtml5#1]
introduction.html has a significant error. It says "Upgrading to the HTML5 doctype won’t break your existing markup, because all the tags defined in HTML 4 are still supported in HTML5."

This is not true. There are many tags defined in HTML 4 that do not exist in HTML 5, e.g. <frame>, <frameset>, <font>, <acronym>, <tt>, etc. There are also many attributes that have been removed, e.g. <a name=>, <meta scheme=>, <script language=>, <table width=>, etc.

I suspect that in reality, most HTML 4 documents will require significant changes to be valid HTML 5 documents - so advising people that they can simply replace their HTML 4 doctype with an HTML 5 doctype without otherwise changing the document itself is quite wrong.

**Comment by jribbens** [comment]
Let me try that again...

Your "Five things you should know about HTML5" document (http://diveintohtml5.com/introduction.html) has a significant error. You say "Upgrading to the HTML5 doctype won’t break your existing markup, because all the tags defined in HTML 4 are still supported in HTML5."

This is not true. There are many tags defined in HTML 4 that do not exist in HTML 5, e.g. `<frame>`, `<frameset>`, `<font>`, `<acronym>`, `<tt>`, etc. There are also many attributes that have been removed, e.g. `<a name=>`, `<meta scheme=>`, `<script language=>`, `<table width=>`, etc.

I suspect that in reality, most HTML 4 documents will require significant changes to be valid HTML 5 documents - so advising people that they can simply replace their HTML 4 doctype with an HTML 5 doctype without otherwise changing the document itself is quite wrong.

**Comment by remy** [comment]
It still doesn't "break your existing markup" - the page still renders perfectly - am I wrong?

What you're actually saying is it won't validate as HTML5 as there are some elements that have been removed, in particular: http://www.w3.org/TR/html5-diff/#absent-elements

However, the document _will still work_ and continue to work.  Just as you can put an HTML5 video element in a page with a HTML4 (3, 2 or 1) doctype, and it will still work.

**Comment by akamike** [comment]
EDIT: Damn you Remy for not only being better looking than me, but also a faster typist!

I agree it could use more accurate wording. Even though the elements are dropped from HTML5 the browser will still support their use as noted at http://www.w3.org/TR/html5-diff/#absent-elements

We also discussed this on HTML5 Doctor, encouraging authors to update their markup as well as the doctype: http://html5doctor.com/absent-elements-and-validation/

Congratulations on opening the first issue. Fancy following that up with the first pull request to suggest an improved introduction? ;)

**Comment by jribbens** [comment]
Remy, it means your markup is now wrong, even if it was right before. Encouraging people to write invalid documents is a bad thing to do, especially when you're basically hiding from them that that's what you're telling them to do.

The introduction seems rather confused as to the difference between browser implementations and HTML 5 anyway. I'm not even sure what "If your web application worked yesterday in HTML 4, it will still work today in HTML5" is trying to say. It certainly doesn't have any clear meaning as written.

I'm making a pull request now.

**Comment by remy** [comment]
@jribbens cheers for the pull, we'll check this out and no doubt pull it in pending review.

Just for the record, and I've said it before, to me: validation does not matter.  It's a tool, **not** a prerequisite to going live. Most people during the "web standards era" were producing XHTML doctype pages, yet serving them as HTML (as IE has no clue about XHTML until IE9) - so none of those pages were "valid".

**Comment by jribbens** [comment]
I think you are wrong that "most people were producing XHTML", and you are certainly wrong that serving valid XHTML as text/html makes it invalid.

I'm not saying that you should insist on validating everything, but equally you shouldn't actively encourage people to create invalid documents. Telling people that sticking an HTML 5 doctype on the top of an HTML 4 document magically turns it into an HTML 5 document is just not true.

**Comment by remy** [comment]
Dude, I'm not telling anyone to do anything. We're just the saps maintain this book after Mark walked away from the table.  As we (Mike specifically) said, it could do with some clarifying.  I don't agree with you, but I'm damned if I'll lose another evening to this futile debate!  It's all good :)

**Comment by jribbens** [comment]
Obviously by "you" I don't mean you personally, I mean the collective maintainers / publishers of this book ;-)

**Comment by remy** [comment]
Sorry - you were also right on the "serving valid XHTML as text/html makes it invalid" - it's not that it's invalid, it's that IE will try to download the page - valid XHTML or not - it's screwed!

**Comment by oli** [comment]
@jribbens — as Remy and Mike mentioned thanks for participating (and submitting a patch!) \o/

I think the confusion is what Mark meant by “break” and “supported” can be interpreted in two ways. However it’s wrong to say “There are many tags defined in HTML 4 that do not exist in HTML 5”. The HTML5 spec defines the elements and attributes you mention in the [Obsolete features section](http://www.whatwg.org/specs/web-apps/current-work/multipage/obsolete.html). Current (and future) browsers must still support these elements to support legacy (pre-HTML5) content, so they won’t break anything. Their use will make an HTML5 document invalid, and authors are encouraged not to use them, but they definitely exist.

This means “sticking an HTML 5 doctype on the top of an HTML 4 document magically turns it into an HTML 5 document is just not true” is incorrect, unless you meant a _valid_ HTML5 document. As the vast majority of the web is invalid I don’t see this as a big issue — validation is a tool to help and a goal to strive for, but not a requirement (phew! :). Changing from a mostly valid HTML 4 document to a mostly valid HTML5 document is still useful, as now you can use the far more detailed HTML5 spec (and validator) for guidance.

re: “I'm not even sure what ‘If your web application worked yesterday in HTML 4, it will still work today in HTML5’ is trying to say”, it means that changing the doctype of a web app from HTML 4 to HTML5 will have zero effect on how the web app works in browsers. By way of contrast, changing to XHTML 1.1 would potentially give you XML errors if served with the recommended mime type.

I think there’s value in some of the cut text, so I suggest merely prepending “While it may no longer validate, ” to the sentence:

> While it may no longer validate, upgrading to the HTML5 doctype won’t break your existing markup, because all the tags defined in HTML 4 are still supported in HTML5.

Thoughts?

**Comment by jribbens** [comment]
> However it’s wrong to say “There are many tags defined in HTML 4 that do not exist in HTML 5”.

Perhaps you should inform the W3C of this, because they disagree. http://www.w3.org/TR/html5-diff/#absent-elements "The following elements are not in HTML5..." Are you maybe unclear as to the meaning of the word "obsolete"?

> This means “sticking an HTML 5 doctype on the top of an HTML 4 document magically turns it into an HTML 5 document is just not true” is incorrect, unless you meant a valid HTML5 document.

Yes. Of course that's what I meant. There is no other possible meaning for that sentence to have.

> As the vast majority of the web is invalid I don’t see this as a big issue

At this risk of repeating myself, you shouldn't actively encourage people to create invalid documents, especially without even warning them that that's what you're doing. I know you want to keep things simple for people, but that doesn't mean that telling them flat-out lies is a good idea.

**Comment by jonathantneal** [comment]
"Upgrading to the HTML5 doctype won’t break your existing markup. Obsolete elements previously defined in HTML 4 will still render in HTML5."

**Comment by jribbens** [comment]
Perhaps that wording with ", even though you should probably get around to updating them at some point" or similar appended. Although it's still somewhat misleading in that it implies the only issue is obsoleted elements, which it isn't.
