### ISSUE TITLE
Update appcache section

### ISSUE THREAD

**Issue by necolas** [html5doctor/diveintohtml5#4]
I believe some of the info in here is outdated

http://diveintohtml5.info/offline.html

e.g, `.manifest` rather than `.appcache`

Thanks

**Comment by oli** [comment]
Thanks for the heads-up. I was hoping someone would jump on this, but it hasn’t happened … yet!
We’ll get there

**Comment by remy** [comment]
@necolas note that the .info domain isn't being run from this repo (@oli - that's right, right?).

Anyway - I've updated it now.  Basically it's just the file extension because Microsoft had the .manifest earmarked for something else...no idea what though!

**Comment by oli** [comment]
@remy yep, although we’re sharing updates with Jon, so it’ll end up there too. Also, thanks for the update!
